-- Restore the canonical 16 cats: UPSERT by slug so existing rows (and the
-- foreign keys that reference them) survive. Anything that was renamed,
-- re-described, or deactivated gets snapped back to the original values
-- and forced active.

insert into public.cats (slug, name, title, personality, description, image_url, story_url, is_active) values
  ('lucy', 'Lucy', 'The Angel Boy', 'Sweet & Gentle',
   'A halo-soft soul who greets every visitor with quiet eyes and a slow blink. Lucy curls into laps like he was made for them.',
   'https://media.ourwebprojects.pro/wp-content/uploads/2026/05/1.png',
   'https://siamesecatcafe.example.com/cats/lucy', true),
  ('charlie', 'Charlie', 'The Comedian King', 'Funny & Playful',
   'The resident jester of the cafe. Charlie will absolutely steal your hair tie, your pen, and your heart - in that order.',
   'https://media.ourwebprojects.pro/wp-content/uploads/2026/05/2.png',
   'https://siamesecatcafe.example.com/cats/charlie', true),
  ('feli', 'Feli', 'The Shy Princess', 'Calm & Elegant',
   'Watchful and refined, Feli observes the world from her velvet cushion and only graces the brave with her purr.',
   'https://media.ourwebprojects.pro/wp-content/uploads/2026/05/3.png',
   'https://siamesecatcafe.example.com/cats/feli', true),
  ('cleo', 'Cleo', 'The First Lady', 'Graceful & Smart',
   'Composed, regal, impossibly poised. Cleo runs the social hour at the cafe with the grace of a seasoned diplomat.',
   'https://media.ourwebprojects.pro/wp-content/uploads/2026/05/1.png',
   'https://siamesecatcafe.example.com/cats/cleo', true),
  ('siam', 'Siam', 'The Curious Explorer', 'Brave & Adventurous',
   'If there is a shelf, Siam has climbed it. If there is a box, Siam has investigated it twice. Born to chart new territory.',
   'https://media.ourwebprojects.pro/wp-content/uploads/2026/05/2.png',
   'https://siamesecatcafe.example.com/cats/siam', true),
  ('muezza', 'Muezza', 'The Little Star', 'Cute & Mischievous',
   'A pocket-sized sparkle of trouble. Muezza was born to be photographed and absolutely knows it.',
   'https://media.ourwebprojects.pro/wp-content/uploads/2026/05/3.png',
   'https://siamesecatcafe.example.com/cats/muezza', true),
  ('comet', 'Comet', 'The Softie', 'Loves Cuddles',
   'A cloud with whiskers. The Comet superpower is melting straight into your arms within four seconds flat.',
   'https://media.ourwebprojects.pro/wp-content/uploads/2026/05/1.png',
   'https://siamesecatcafe.example.com/cats/comet', true),
  ('malee', 'Malee', 'The Talkative', 'Loves Attention',
   'Malee has a lot to say and absolutely will say it. Bring snacks, bring patience, bring an audience.',
   'https://media.ourwebprojects.pro/wp-content/uploads/2026/05/2.png',
   'https://siamesecatcafe.example.com/cats/malee', true),
  ('lila', 'Lila', 'The Independent', 'Confident & Cool',
   'Lila walks alone by choice, not by chance. Earn her trust and you have earned a quiet, unshakable friend.',
   'https://media.ourwebprojects.pro/wp-content/uploads/2026/05/3.png',
   'https://siamesecatcafe.example.com/cats/lila', true),
  ('luca', 'Luca', 'The Brave Heart', 'Strong & Loyal',
   'Guardian of the front window. Luca was rescued from the street and has been protecting his family ever since.',
   'https://media.ourwebprojects.pro/wp-content/uploads/2026/05/1.png',
   'https://siamesecatcafe.example.com/cats/luca', true),
  ('pho', 'Pho', 'The Sweetheart', 'Kind & Gentle',
   'Pho greets every cat and every human with the same patient warmth. The quiet healer of the cafe.',
   'https://media.ourwebprojects.pro/wp-content/uploads/2026/05/2.png',
   'https://siamesecatcafe.example.com/cats/pho', true),
  ('mia', 'Mia', 'The Foodie', 'Always Hungry',
   'Mia has a sixth sense for treat jars. Approach with snacks and prepare for full-court diplomatic negotiation.',
   'https://media.ourwebprojects.pro/wp-content/uploads/2026/05/3.png',
   'https://siamesecatcafe.example.com/cats/mia', true),
  ('nina', 'Nina', 'The Dancer', 'Playful & Energetic',
   'Spins, leaps, twirls. Nina turns every laser-pointer game into a one-cat ballet.',
   'https://media.ourwebprojects.pro/wp-content/uploads/2026/05/1.png',
   'https://siamesecatcafe.example.com/cats/nina', true),
  ('mira', 'Mira', 'The Dreamer', 'Calm & Thoughtful',
   'Mira spends her afternoons watching the rain. A quiet philosopher with very strong opinions about sunbeams.',
   'https://media.ourwebprojects.pro/wp-content/uploads/2026/05/2.png',
   'https://siamesecatcafe.example.com/cats/mira', true),
  ('flow', 'Flow', 'The Queen', 'Elegant & Regal',
   'Flow holds court from the highest shelf. Subjects may approach if invited, and only if their hands are clean.',
   'https://media.ourwebprojects.pro/wp-content/uploads/2026/05/3.png',
   'https://siamesecatcafe.example.com/cats/flow', true),
  ('soul', 'Soul', 'The Protector', 'Strong & Caring',
   'Soul keeps watch over the youngest kittens. Big heart, bigger paws, biggest sense of duty.',
   'https://media.ourwebprojects.pro/wp-content/uploads/2026/05/1.png',
   'https://siamesecatcafe.example.com/cats/soul', true)
on conflict (slug) do update set
  name        = excluded.name,
  title       = excluded.title,
  personality = excluded.personality,
  description = excluded.description,
  image_url   = excluded.image_url,
  story_url   = excluded.story_url,
  is_active   = true;

-- Audit afterwards so we can see the result.
select count(*) as total,
       count(*) filter (where is_active) as active
from public.cats;
