/**
 * Supabase Database type — generated by hand for Phase 3A.
 *
 * Once the schema is deployed and we have the Supabase CLI configured,
 * regenerate this file automatically with:
 *
 *   supabase gen types typescript --linked > lib/supabase/database.types.ts
 *
 * Keeping this file in sync with the SQL migration is required for type
 * safety on every `supabase.from(...).select()` / `.insert()` call.
 */

export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[];

export type Database = {
  public: {
    Tables: {
      // -----------------------------------------------------------------
      voters: {
        Row: {
          id: string;
          name: string;
          email: string;
          phone: string | null;
          invitation_code: string;
          device_id: string;
          user_id: string | null;
          is_admin: boolean;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          name: string;
          email: string;
          phone?: string | null;
          invitation_code: string;
          device_id: string;
          user_id?: string | null;
          is_admin?: boolean;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          name?: string;
          email?: string;
          phone?: string | null;
          invitation_code?: string;
          device_id?: string;
          user_id?: string | null;
          is_admin?: boolean;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [];
      };

      // -----------------------------------------------------------------
      cats: {
        Row: {
          id: string;
          slug: string;
          name: string;
          title: string;
          personality: string;
          description: string;
          image_url: string;
          story_url: string | null;
          is_active: boolean;
          created_at: string;
        };
        Insert: {
          id?: string;
          slug: string;
          name: string;
          title: string;
          personality: string;
          description: string;
          image_url: string;
          story_url?: string | null;
          is_active?: boolean;
          created_at?: string;
        };
        Update: {
          id?: string;
          slug?: string;
          name?: string;
          title?: string;
          personality?: string;
          description?: string;
          image_url?: string;
          story_url?: string | null;
          is_active?: boolean;
          created_at?: string;
        };
        Relationships: [];
      };

      // -----------------------------------------------------------------
      hearts: {
        Row: {
          id: string;
          voter_id: string;
          cat_id: string;
          device_id: string;
          hearted_at: string;
          next_available_at: string;
          season_id: string | null;
          created_at: string;
        };
        Insert: {
          id?: string;
          voter_id: string;
          cat_id: string;
          device_id: string;
          hearted_at?: string;
          next_available_at: string;
          season_id?: string | null;
          created_at?: string;
        };
        Update: {
          id?: string;
          voter_id?: string;
          cat_id?: string;
          device_id?: string;
          hearted_at?: string;
          next_available_at?: string;
          season_id?: string | null;
          created_at?: string;
        };
        Relationships: [
          {
            foreignKeyName: "hearts_voter_id_fkey";
            columns: ["voter_id"];
            isOneToOne: false;
            referencedRelation: "voters";
            referencedColumns: ["id"];
          },
          {
            foreignKeyName: "hearts_cat_id_fkey";
            columns: ["cat_id"];
            isOneToOne: false;
            referencedRelation: "cats";
            referencedColumns: ["id"];
          },
        ];
      };

      // -----------------------------------------------------------------
      cat_affection: {
        Row: {
          id: string;
          voter_id: string;
          cat_id: string;
          hearts_given: number;
          affection_level: number;
          last_hearted_at: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          voter_id: string;
          cat_id: string;
          hearts_given?: number;
          affection_level?: number;
          last_hearted_at?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          voter_id?: string;
          cat_id?: string;
          hearts_given?: number;
          affection_level?: number;
          last_hearted_at?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [
          {
            foreignKeyName: "cat_affection_voter_id_fkey";
            columns: ["voter_id"];
            isOneToOne: false;
            referencedRelation: "voters";
            referencedColumns: ["id"];
          },
          {
            foreignKeyName: "cat_affection_cat_id_fkey";
            columns: ["cat_id"];
            isOneToOne: false;
            referencedRelation: "cats";
            referencedColumns: ["id"];
          },
        ];
      };

      // -----------------------------------------------------------------
      coupons: {
        Row: {
          id: string;
          voter_id: string;
          cat_id: string;
          coupon_code: string;
          reward_title: string;
          issued_at: string;
          expires_at: string;
          status: "active" | "redeemed" | "expired";
          redeemed_at: string | null;
          created_at: string;
        };
        Insert: {
          id?: string;
          voter_id: string;
          cat_id: string;
          coupon_code: string;
          reward_title: string;
          issued_at?: string;
          expires_at: string;
          status?: "active" | "redeemed" | "expired";
          redeemed_at?: string | null;
          created_at?: string;
        };
        Update: {
          id?: string;
          voter_id?: string;
          cat_id?: string;
          coupon_code?: string;
          reward_title?: string;
          issued_at?: string;
          expires_at?: string;
          status?: "active" | "redeemed" | "expired";
          redeemed_at?: string | null;
          created_at?: string;
        };
        Relationships: [
          {
            foreignKeyName: "coupons_voter_id_fkey";
            columns: ["voter_id"];
            isOneToOne: false;
            referencedRelation: "voters";
            referencedColumns: ["id"];
          },
          {
            foreignKeyName: "coupons_cat_id_fkey";
            columns: ["cat_id"];
            isOneToOne: false;
            referencedRelation: "cats";
            referencedColumns: ["id"];
          },
        ];
      };

      // -----------------------------------------------------------------
      wheel_spins: {
        Row: {
          id: string;
          voter_id: string;
          cat_id: string;
          heart_id: string;
          result_type: "win" | "lose";
          reward_title: string;
          coupon_id: string | null;
          spun_at: string;
        };
        Insert: {
          id?: string;
          voter_id: string;
          cat_id: string;
          heart_id: string;
          result_type: "win" | "lose";
          reward_title: string;
          coupon_id?: string | null;
          spun_at?: string;
        };
        Update: {
          id?: string;
          voter_id?: string;
          cat_id?: string;
          heart_id?: string;
          result_type?: "win" | "lose";
          reward_title?: string;
          coupon_id?: string | null;
          spun_at?: string;
        };
        Relationships: [
          {
            foreignKeyName: "wheel_spins_voter_id_fkey";
            columns: ["voter_id"];
            isOneToOne: false;
            referencedRelation: "voters";
            referencedColumns: ["id"];
          },
          {
            foreignKeyName: "wheel_spins_cat_id_fkey";
            columns: ["cat_id"];
            isOneToOne: false;
            referencedRelation: "cats";
            referencedColumns: ["id"];
          },
          {
            foreignKeyName: "wheel_spins_heart_id_fkey";
            columns: ["heart_id"];
            isOneToOne: true;
            referencedRelation: "hearts";
            referencedColumns: ["id"];
          },
          {
            foreignKeyName: "wheel_spins_coupon_id_fkey";
            columns: ["coupon_id"];
            isOneToOne: false;
            referencedRelation: "coupons";
            referencedColumns: ["id"];
          },
        ];
      };

      // -----------------------------------------------------------------
      invitation_codes: {
        Row: {
          id: string;
          code: string;
          label: string | null;
          is_active: boolean;
          usage_count: number;
          created_at: string;
        };
        Insert: {
          id?: string;
          code: string;
          label?: string | null;
          is_active?: boolean;
          usage_count?: number;
          created_at?: string;
        };
        Update: {
          id?: string;
          code?: string;
          label?: string | null;
          is_active?: boolean;
          usage_count?: number;
          created_at?: string;
        };
        Relationships: [];
      };

      // -----------------------------------------------------------------
      // -----------------------------------------------------------------
      voting_seasons: {
        Row: {
          id: string;
          name: string;
          starts_at: string;
          ends_at: string;
          status: "open" | "closed";
          winner_cat_id: string | null;
          created_at: string;
        };
        Insert: {
          id?: string;
          name: string;
          starts_at: string;
          ends_at: string;
          status?: "open" | "closed";
          winner_cat_id?: string | null;
          created_at?: string;
        };
        Update: {
          id?: string;
          name?: string;
          starts_at?: string;
          ends_at?: string;
          status?: "open" | "closed";
          winner_cat_id?: string | null;
          created_at?: string;
        };
        Relationships: [];
      };

      // -----------------------------------------------------------------
      wheel_rewards: {
        Row: {
          id: string;
          label: string;
          wheel_label: string;
          emoji: string;
          type: "win" | "lose";
          coupon_title: string | null;
          sort_order: number;
          is_active: boolean;
          created_at: string;
        };
        Insert: {
          id?: string;
          label: string;
          wheel_label: string;
          emoji: string;
          type: "win" | "lose";
          coupon_title?: string | null;
          sort_order?: number;
          is_active?: boolean;
          created_at?: string;
        };
        Update: {
          id?: string;
          label?: string;
          wheel_label?: string;
          emoji?: string;
          type?: "win" | "lose";
          coupon_title?: string | null;
          sort_order?: number;
          is_active?: boolean;
          created_at?: string;
        };
        Relationships: [];
      };

      app_settings: {
        Row: {
          id: string;
          setting_key: string;
          setting_value: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          setting_key: string;
          setting_value: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          setting_key?: string;
          setting_value?: string;
          updated_at?: string;
        };
        Relationships: [];
      };
    };
    Views: {
      hearts_view: {
        Row: {
          id: string;
          voter_name: string;
          voter_email: string;
          cat_name: string;
          cat_slug: string;
          hearted_at: string;
          next_available_at: string;
          device_id: string;
          voter_id: string;
          cat_id: string;
        };
        Relationships: [];
      };
      affection_view: {
        Row: {
          id: string;
          voter_name: string;
          voter_email: string;
          cat_name: string;
          cat_slug: string;
          hearts_given: number;
          affection_level: number;
          last_hearted_at: string | null;
          voter_id: string;
          cat_id: string;
        };
        Relationships: [];
      };
      wheel_spins_view: {
        Row: {
          id: string;
          voter_name: string;
          voter_email: string;
          cat_name: string;
          result_type: "win" | "lose";
          reward_title: string;
          coupon_code: string | null;
          spun_at: string;
          voter_id: string;
          cat_id: string;
          heart_id: string;
          coupon_id: string | null;
        };
        Relationships: [];
      };
      coupons_view: {
        Row: {
          id: string;
          coupon_code: string;
          voter_name: string;
          voter_email: string;
          cat_name: string;
          reward_title: string;
          status: "active" | "redeemed" | "expired";
          issued_at: string;
          expires_at: string;
          redeemed_at: string | null;
          voter_id: string;
          cat_id: string;
        };
        Relationships: [];
      };
    };
    Functions: { [_ in never]: never };
    Enums: { [_ in never]: never };
    CompositeTypes: { [_ in never]: never };
  };
};

// =============================================================================
// Convenience row aliases — use these in app code instead of the deeply nested
// `Database["public"]["Tables"]["voters"]["Row"]` form.
// =============================================================================

export type VoterRow = Database["public"]["Tables"]["voters"]["Row"];
export type CatRow = Database["public"]["Tables"]["cats"]["Row"];
export type HeartRow = Database["public"]["Tables"]["hearts"]["Row"];
export type CatAffectionRow =
  Database["public"]["Tables"]["cat_affection"]["Row"];
export type CouponRow = Database["public"]["Tables"]["coupons"]["Row"];
export type WheelSpinRow = Database["public"]["Tables"]["wheel_spins"]["Row"];
export type InvitationCodeRow =
  Database["public"]["Tables"]["invitation_codes"]["Row"];
export type AppSettingRow =
  Database["public"]["Tables"]["app_settings"]["Row"];
export type VotingSeasonRow =
  Database["public"]["Tables"]["voting_seasons"]["Row"];
export type WheelRewardRow =
  Database["public"]["Tables"]["wheel_rewards"]["Row"];

// Status string literals — exported so callers can branch on them safely.
export type CouponStatus = "active" | "redeemed" | "expired";
export type WheelResultType = "win" | "lose";
